name = "OdsReaders"
uuid = "d106bba2-c2c2-11e8-2b58-7bbef29e2cf6"
authors = ["mkatase <michimoto.katase@gmail.com>"]
version = "0.2.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
